version: '3.4'

services: 

  frontend:
    image: final-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    environment: 
      - backendUrl=http://final-backend
    ports:
      - "81:80"
    depends_on: 
      - backend
  backend:
    image: final-backend
    build: 
      context: backend
      dockerfile: Dockerfile
    ports: 
      - "80:80"