version: '3.4'

services: 

  frontend:
    image: final-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    environment: 
      - REACT_APP_API_URL=http://final-backend/
    ports:
      - "81:3000"
    depends_on: 
      - backend
  backend:
    image: final-backend
    build: 
      context: backend/FinalProject
      dockerfile: Dockerfile
    ports: 
      - "80:80"