version: "3"
services:
  sonarqube:
    image: sonarqube:lts
    ports:
      - 9000:9000
    networks:
      - mynetwork
    environment:
      - SONAR_FORCEAUTHENTICATION=false
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    ports:
      - 8080:8080
    networks:
      - mynetwork
networks:
  mynetwork: