apiVersion: apps/v1
kind: Deployment
metadata:
  name: finalfrontend
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: finalfrontend
    spec:
      containers:
      - name: finalfrontend
        image: bglyvv/final-frontend:latest
        env:
          - name: REACT_APP_API_URL
            value: http://${FINALBACKEND_SERVICE_HOST}:${FINALBACKEND_SERVICE_PORT}
  selector:
    matchLabels:
      app: finalfrontend