apiVersion: apps/v1
kind: Deployment
metadata:
  name: finalbackend
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: finalbackend
    spec:
      containers:
      - name: finalbackend
        image: bglyvv/final-backend
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
      app: finalbackend

---
apiVersion: v1
kind: Service
metadata:
  name: finalbackend
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: finalbackend